# Generated by Django 3.0.11 on 2022-04-06 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Living",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "living_accord",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Hydrophyt"),
                            ("2", "krautiger"),
                            ("3", "Chamaephyt"),
                            ("4", "Geophyt"),
                            ("5", "Hemikryptophyt"),
                            ("6", "Nanophanerophyt"),
                            ("7", "Phanerophyt"),
                            ("8", "Therophyt"),
                            ("9", "holziger Chamaephyt"),
                            ("10", "Liane / Spreitzklimmer"),
                            ("11", "Epiphyt"),
                            ("12", "Halbparasit"),
                            ("13", "Vollparasit"),
                        ],
                        help_text="Klare Zuweisung einer Kategorie, erweiterbar:",
                        max_length=22,
                        null=True,
                        verbose_name="Lebensform nach Raukiær (1919)",
                    ),
                ),
                (
                    "spec_living",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Besonderes zur Lebensweise",
                    ),
                ),
                (
                    "life_span",
                    models.CharField(
                        choices=[
                            ("1", "ausdauernd, sehr kurz überdauernd ( < 50 J)?"),
                            ("2", "ausdauernd, kurz überdauernd(50 - 100J)"),
                            ("3", "ausdauernd, mäßig dauerhaft(100 - 300J)"),
                            ("4", "ausdauernd, dauerhaft(300 - 500J)"),
                            ("5", "ausdauernd, sehr dauerhaft(ü 500J)"),
                        ],
                        max_length=44,
                        verbose_name="Lebensdauer",
                    ),
                ),
                (
                    "extra",
                    models.TextField(
                        blank=True,
                        help_text="Nur solitär stehend so alt werdend; unter Konkurrenz kurzlebiger",
                        max_length=500,
                        null=True,
                        verbose_name="Weiteres zur Lebensdauer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lebensweise",
                "verbose_name_plural": "Lebensweisen",
            },
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={"verbose_name": "Pflanze", "verbose_name_plural": "Pflanzen",},
        ),
        migrations.CreateModel(
            name="Taxonomy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bot_name",
                    models.CharField(
                        help_text="Gattung und Art, ggf. Unterart/ Variation, ggf. Sorte",
                        max_length=100,
                        verbose_name="Botanischer Name",
                    ),
                ),
                (
                    "de_name",
                    models.CharField(max_length=100, default="Test", verbose_name="Deutscher Name"),
                ),
                (
                    "relevant_cultivar",
                    models.TextField(
                        blank=True,
                        help_text="Name der Sorte' - prägnantes Merkmal",
                        max_length=500,
                        null=True,
                        verbose_name="Relevante Sorten",
                    ),
                ),
                (
                    "synonyms",
                    models.CharField(
                        blank=True,
                        help_text="Gattung und Art, ggf. Unterart/ Variation, Sorte",
                        max_length=100,
                        null=True,
                        verbose_name="Synonyme",
                    ),
                ),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("1", "Amaryllidaceae(Narzissengewächse)"),
                            ("2", "Apiaceae (Doldenblütler)"),
                            ("3", "Asteraceae(Korbblütler)"),
                            ("4", "Boraginaceae(Raublattgewächse)"),
                            ("5", "Brassicaceae(Kreuzblütengewächse)"),
                            ("6", "Campanulaceae(Glockenblumengewächse)"),
                            ("7", "Caryophyllaceae(Nelkengewächse)"),
                            ("8", "Ericaceae(Heidekrautgewächse)"),
                            ("9", "Euphorbiaceae(Wolfsmilchgewächse)"),
                            ("10", "Fabaceae(Hülsenfrüchtler)"),
                            ("11", "Fagaceae(Buchengewächse)"),
                            ("12", "Gentianaceae(Enziangewächse)"),
                            ("13", "Iridaceae(Schwertliliengewächse)"),
                            ("14", "Lamiaceae(Lippenblütler)"),
                            ("15", "Liliaceae(Liliengewächse)"),
                            ("16", "Magnoliaceae(Magnoliengewächse)"),
                            ("17", "Malvaceae(Malvengewächse)"),
                            ("18", "Nymphaeaceae(Seerosengewächse)"),
                            ("19", "Orchidaceae(Orchideengewächse)"),
                            ("20", "Papaveraceae(Mohngewächse)"),
                            ("21", "Poaceae(Süssgräser)"),
                            ("22", "Primulaceae(Primelgewächse)"),
                            ("23", "Ranunculaceae(Hahnenfussgewächse)"),
                            ("24", "Rosaceae(Rosengewächse)"),
                            ("25", "Scrophulariaceae(Rachenblütler)"),
                            ("26", "Solanaceae(Nachtschattengewächse)"),
                        ],
                        max_length=36,
                        verbose_name="Familie - botanischer Name (deutscher Name)",
                    ),
                ),
                (
                    "de_domestic",
                    models.CharField(
                        choices=[("ja", "ja"), ("nein", "nein")],
                        max_length=4,
                        verbose_name="In Deutschland heimisch",
                    ),
                ),
                (
                    "de_hardy",
                    models.CharField(
                        blank=True,
                        choices=[("ja", "ja"), ("nein", "nein")],
                        help_text="Bitte nur ausfüllen, wenn heimisch = nein",
                        max_length=4,
                        null=True,
                        verbose_name="In Deutschland winterhart",
                    ),
                ),
                (
                    "living",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="living",
                        to="planty_plant_content.Living",
                        verbose_name="Lebensweise",
                    ),
                ),
                (
                    "plant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="living",
                        to="planty_plant_content.Plant",
                        verbose_name="Pflanze",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taxonomie und Lebensweise",
                "verbose_name_plural": "Taxonomien und Lebensweisen",
            },
        ),
    ]
