# Generated by Django 3.0.11 on 2022-04-06 18:08

import django.db.models.deletion
import solid_backend.content.fields
from django.db import migrations, models

import planty_plant_content.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "planty_plant_content",
            "0002_ecologyandnatlocation_natbehavior_natoccurence_zeigervalues",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Bark",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Jung- und Altzustand",
                        max_length=100,
                        null=True,
                        verbose_name="Farbe",
                    ),
                ),
                (
                    "surface",
                    models.CharField(
                        blank=True,
                        help_text="Jung- und Altzustand",
                        max_length=100,
                        null=True,
                        verbose_name="Oberfläche/Struktur",
                    ),
                ),
                (
                    "structure",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Aufbau"
                    ),
                ),
                (
                    "extras",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Weitere Merkmale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blossom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stand",
                    models.CharField(
                        blank=True,
                        help_text="Formulierungen entspr. Schmeil-Fitschen",
                        max_length=100,
                        null=True,
                        verbose_name="Blütenstand",
                    ),
                ),
                (
                    "form_single_blossom",
                    models.CharField(
                        blank=True,
                        help_text="Formulierungen entspr. Schmeil-Fitschen",
                        max_length=100,
                        null=True,
                        verbose_name="Form der Einzelblüte",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        help_text="Einzelblüte/Blütenbestandteile/Blütenstand in mm bis cm, Eingabe der Einheit",
                        max_length=100,
                        null=True,
                        verbose_name="Größe",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Grundfarbe und besondere Farbnuancen",
                        max_length=100,
                        null=True,
                        verbose_name="Farbe",
                    ),
                ),
                (
                    "pollination",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "abiotische Bestäubung"),
                            ("2", "Fledermausbestäubung"),
                            ("3", "Geitonogamie"),
                            ("4", "Insektenbestäubung"),
                            ("5", "Kleistogamie"),
                            ("6", "Pseudokleistogamie"),
                            ("7", "Selbstbestäubung"),
                            ("8", "Schneckenbestäubung"),
                            ("9", "Vogelbestäubung"),
                            ("10", "Wasserbestäubung"),
                            ("11", "Windbestäubung"),
                            ("12", "Tierbestäubung"),
                        ],
                        help_text="für generative Vermehrung",
                        max_length=2,
                        null=True,
                        verbose_name="Bestäubungsfaktoren ",
                    ),
                ),
                (
                    "extras",
                    models.TextField(
                        blank=True,
                        help_text="",
                        max_length=500,
                        null=True,
                        verbose_name="Weitere Merkmale ",
                    ),
                ),
                (
                    "main_blooming_period",
                    solid_backend.content.fields.FromToConcatField(
                        blank=True,
                        default="",
                        from_choices=(
                            ("I", "I"),
                            ("II", "II"),
                            ("III", "III"),
                            ("IV", "IV"),
                            ("V", "V"),
                            ("VI", "VI"),
                            ("VII", "VII"),
                            ("VIII", "VIII"),
                            ("IX", "IX"),
                            ("X", "X"),
                            ("XI", "XI"),
                            ("XII", "XII"),
                        ),
                        max_length=100,
                        to_choices=(
                            ("I", "I"),
                            ("II", "II"),
                            ("III", "III"),
                            ("IV", "IV"),
                            ("V", "V"),
                            ("VI", "VI"),
                            ("VII", "VII"),
                            ("VIII", "VIII"),
                            ("IX", "IX"),
                            ("X", "X"),
                            ("XI", "XI"),
                            ("XII", "XII"),
                        ),
                        verbose_name="Hauptblütezeit",
                    ),
                ),
                (
                    "after_blooming_period",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nachblüte, Nebenblüte",
                    ),
                ),
                (
                    "phenology_blooming_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Vorfrühling"),
                            ("2", "Beginn Erstfrühling"),
                            ("3", "Ende Erstfrühling"),
                            ("4", "Beginn Vollfrühling"),
                            ("5", "Ende Vollfrühling"),
                            ("6", "Beginn Frühsommer"),
                            ("7", "Ende Frühsommer"),
                            ("8", "Hochsommer"),
                            ("9", "Frühherbst"),
                            ("10", "Herbst"),
                            ("11", "Winter"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Phänologische Blühphasen ",
                    ),
                ),
                (
                    "age_at_frist_bloom",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Alter bei erster Blüte",
                    ),
                ),
                (
                    "note_to_bloom",
                    models.TextField(
                        blank=True,
                        help_text="",
                        max_length=500,
                        null=True,
                        verbose_name="Hinweise zur Blütezeit",
                    ),
                ),
                (
                    "odor",
                    models.CharField(
                        blank=True,
                        help_text="Intensität, Aroma",
                        max_length=100,
                        null=True,
                        verbose_name="Geruch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fruit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Form"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Größe"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Farbe"
                    ),
                ),
                (
                    "ripeness",
                    solid_backend.content.fields.FromToConcatField(
                        blank=True,
                        default="",
                        from_choices=(
                            ("I", "I"),
                            ("II", "II"),
                            ("III", "III"),
                            ("IV", "IV"),
                            ("V", "V"),
                            ("VI", "VI"),
                            ("VII", "VII"),
                            ("VIII", "VIII"),
                            ("IX", "IX"),
                            ("X", "X"),
                            ("XI", "XI"),
                            ("XII", "XII"),
                        ),
                        max_length=100,
                        to_choices=(
                            ("I", "I"),
                            ("II", "II"),
                            ("III", "III"),
                            ("IV", "IV"),
                            ("V", "V"),
                            ("VI", "VI"),
                            ("VII", "VII"),
                            ("VIII", "VIII"),
                            ("IX", "IX"),
                            ("X", "X"),
                            ("XI", "XI"),
                            ("XII", "XII"),
                        ),
                        verbose_name="Reife",
                    ),
                ),
                (
                    "seed_intensity",
                    models.CharField(
                        blank=True,
                        help_text="generative Vermehrung",
                        max_length=100,
                        null=True,
                        verbose_name="Intensität der Versamung ",
                    ),
                ),
                (
                    "extras",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Weitere Merkmale ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Habitus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "height",
                    models.CharField(
                        blank=True,
                        help_text="in m, Engabe der Einheut",
                        max_length=100,
                        null=True,
                        verbose_name="Wuchshöhe",
                    ),
                ),
                (
                    "width",
                    models.CharField(
                        blank=True,
                        help_text="in m, Engabe der Einheut",
                        max_length=100,
                        null=True,
                        verbose_name="Wuchsbreite",
                    ),
                ),
                (
                    "grow_style",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Wüchsigkeit",
                    ),
                ),
                (
                    "dimension_extra",
                    models.TextField(
                        blank=True,
                        help_text="Veränderte Größen bei speziellen Bedingungen",
                        max_length=500,
                        null=True,
                        verbose_name="Weiteres zur Dimension",
                    ),
                ),
                (
                    "grow_form",
                    models.CharField(max_length=100, verbose_name="Wuchsform"),
                ),
                (
                    "grow_extra",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Weiteres zum Wuchs",
                    ),
                ),
                (
                    "similar_kinds",
                    models.TextField(
                        blank=True,
                        help_text="('leicht zu verwechseln mit', Merkmal)",
                        max_length=500,
                        null=True,
                        verbose_name="Ähnliche Arten / Differenzialmerkmale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Leaf",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form",
                    models.CharField(
                        help_text="Formulierungen entspr. Schmeil-Fitschen",
                        max_length=100,
                        verbose_name="Form",
                    ),
                ),
                (
                    "edge_form",
                    models.CharField(
                        blank=True,
                        help_text="Formulierungen entspr. Schmeil-Fitschen",
                        max_length=100,
                        null=True,
                        verbose_name="Randform",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        help_text="in mm/cm, Eingabe der Einheit",
                        max_length=100,
                        null=True,
                        verbose_name="Größe",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Farbe"
                    ),
                ),
                (
                    "panasch",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Panschierung",
                    ),
                ),
                (
                    "color_winter",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Farbe in Herbst/Winter",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Formulierungen entspr. Schmeil-Fitschen",
                        max_length=100,
                        verbose_name="Stellung",
                    ),
                ),
                (
                    "nerves",
                    models.CharField(
                        blank=True,
                        help_text="Formulierungen entspr. Schmeil-Fitschen",
                        max_length=100,
                        null=True,
                        verbose_name="Nervatur",
                    ),
                ),
                (
                    "endurance",
                    planty_plant_content.models.ChoiceArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("1", "immergrün"),
                                ("2", "überwinternd grün / wintergrün"),
                                ("3", "sommergrün"),
                                ("4", "vorsommergrün"),
                            ],
                            max_length=2,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Ausdauer",
                    ),
                ),
                (
                    "anatomy",
                    planty_plant_content.models.ChoiceArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("1", "hydromorph"),
                                ("2", "blattsukkulent"),
                                ("3", "helomorph"),
                                ("4", "mesomorph"),
                                ("5", "skleromorph / xeromorph"),
                                ("6", "hygromorph"),
                            ],
                            max_length=2,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Anatomie",
                    ),
                ),
                (
                    "budding",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Vorfrühling"),
                            ("2", "Beginn Erstfrühling"),
                            ("3", "Ende Erstfrühling"),
                            ("4", "Beginn Vollfrühling"),
                            ("5", "Ende Vollfrühling"),
                            ("6", "Beginn Frühsommer"),
                            ("7", "Ende Frühsommer"),
                            ("8", "Hochsommer"),
                            ("9", "Frühherbst"),
                            ("10", "Herbst"),
                            ("11", "Winter"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Blattaustrieb (phänologisch)",
                    ),
                ),
                (
                    "budding_time",
                    models.CharField(
                        blank=True,
                        help_text="Wenn Besonderheit im Zeitpunkt des Neuaustriebs",
                        max_length=100,
                        null=True,
                        verbose_name="Zeitpunkt des Austriebs",
                    ),
                ),
                (
                    "odor",
                    models.TextField(
                        blank=True,
                        help_text="Intensität, Aroma",
                        max_length=500,
                        null=True,
                        verbose_name="Geruch",
                    ),
                ),
                (
                    "extras",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Weitere Merkmale ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Root",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Typ"
                    ),
                ),
                (
                    "depth",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Tiefe, konkret",
                    ),
                ),
                (
                    "spread",
                    models.TextField(
                        blank=True,
                        help_text="Vegetative Ausbreitung und Speicherorgane",
                        max_length=500,
                        null=True,
                        verbose_name="",
                    ),
                ),
                (
                    "sensitivity",
                    models.CharField(
                        blank=True,
                        help_text="Empfindlichkeiten/Fähigkeiten",
                        max_length=100,
                        null=True,
                        verbose_name="Empfindlichkeit",
                    ),
                ),
                (
                    "extras",
                    models.TextField(
                        blank=True,
                        help_text="Besonderes Verhalten",
                        max_length=500,
                        null=True,
                        verbose_name="Weitere Merkmale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sprout",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch_form",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Form Äste/ Triebe/ Verzweigung",
                    ),
                ),
                (
                    "buds",
                    models.TextField(
                        help_text="Form und Farbe",
                        max_length=500,
                        verbose_name="Knospen",
                    ),
                ),
                (
                    "leaf_scar",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Blattnarbe"
                    ),
                ),
                (
                    "odor",
                    models.CharField(
                        blank=True,
                        help_text="Intensität, Aroma",
                        max_length=100,
                        null=True,
                        verbose_name="Geruch",
                    ),
                ),
                (
                    "extras",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Weitere Merkmale ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appearance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bark",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appearance",
                        to="planty_plant_content.Bark",
                        verbose_name="Rinde",
                    ),
                ),
                (
                    "blossom",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appearance",
                        to="planty_plant_content.Blossom",
                        verbose_name="Blüte",
                    ),
                ),
                (
                    "fruit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appearance",
                        to="planty_plant_content.Fruit",
                        verbose_name="Frucht",
                    ),
                ),
                (
                    "habitus",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appearance",
                        to="planty_plant_content.Habitus",
                        verbose_name="Habitus",
                    ),
                ),
                (
                    "leaf",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appearance",
                        to="planty_plant_content.Leaf",
                        verbose_name="Blatt",
                    ),
                ),
                (
                    "plant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appearance",
                        to="planty_plant_content.Plant",
                        verbose_name="Pflanze",
                    ),
                ),
                (
                    "root",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appearance",
                        to="planty_plant_content.Root",
                        verbose_name="Wurzel",
                    ),
                ),
                (
                    "sprout",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appearance",
                        to="planty_plant_content.Sprout",
                        verbose_name="Trieb",
                    ),
                ),
            ],
            options={
                "verbose_name": "Habitus und Erscheinung",
                "verbose_name_plural": "Habitus und Erscheinungen",
            },
        ),
    ]
