# Generated by Django 3.0.11 on 2022-04-06 20:06

from django.db import migrations, models
import django.db.models.deletion
import planty_plant_content.models


class Migration(migrations.Migration):

    dependencies = [
        ('planty_plant_content', '0005_auto_20220406_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReproductionAndProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reproduction_type', planty_plant_content.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('1', 'Aussat'), ('2', 'Stecklingsvermehrung'), ('3', 'Brutknöllchen'), ('4', 'Ableger')], max_length=2), blank=True, null=True, size=None, verbose_name='Art der Vermehrung')),
                ('sprout_behavior', planty_plant_content.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('1', 'Kaltkeimer'), ('2', 'Warmkeimer'), ('3', 'Lichtkeimer'), ('4', 'Normalkeimer')], max_length=2), blank=True, null=True, size=None, verbose_name='Keimverhalten')),
                ('refinement', models.TextField(blank=True, max_length=500, null=True, verbose_name='Veredelungsfaktoren')),
                ('extra_reproducttion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Weiteres zur Vermehrung ')),
                ('cultivation_req', models.TextField(blank=True, help_text='Saattiefe, Keimtemperatur, Substrate, Wundverschluss, etc.', max_length=500, null=True, verbose_name='Anzuchtbedingungen ')),
                ('culture_req', models.TextField(blank=True, help_text='nur bei dauerhafter Kultur, z.B. Baumschule', max_length=500, null=True, verbose_name='Kulturbedingungen (Outdoor)')),
                ('lighting_criteria', models.TextField(blank=True, max_length=500, null=True, verbose_name='Beleuchtungskriterien')),
                ('tempertaure_criteria', models.TextField(blank=True, max_length=500, null=True, verbose_name='Temperaturkriterien')),
                ('cilture_substrates', models.TextField(blank=True, max_length=500, null=True, verbose_name='Kultursubstrate')),
                ('fertilization', models.TextField(blank=True, help_text='in Kultur', max_length=500, null=True, verbose_name='Düngung/Wachstumsförderung ')),
                ('extra_culture', models.TextField(blank=True, help_text='nur bei dauerhafter Kultur, z.B. Gewächshaus', max_length=500, null=True, verbose_name='Weitere Kulturbedingungen (Indoor)')),
                ('extra_production', models.TextField(blank=True, max_length=500, null=True, verbose_name='Weiteres zu Produktion')),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reproduction_and_production', to='planty_plant_content.Plant', verbose_name='Pflanze')),
            ],
            options={
                'verbose_name': 'Vermehrung / Produktion',
                'verbose_name_plural': 'Vermehrungen / Produktionen',
            },
        ),
    ]
