# Generated by Django 3.0.11 on 2022-04-06 20:48

import django.db.models.deletion
from django.db import migrations, models

import planty_plant_content.models


class Migration(migrations.Migration):

    dependencies = [
        ("planty_plant_content", "0006_reproductionandproduction"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaunaUsability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bee_plant",
                    planty_plant_content.models.ChoiceArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("1", "Nektar"),
                                ("2", "Pollen"),
                                ("3", "Aufenthalt"),
                                ("4", "Nistmaterial"),
                            ],
                            max_length=2,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Bienenpflanze",
                    ),
                ),
                (
                    "extra_bee",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Hinweise zur Bienenpflanze",
                    ),
                ),
                (
                    "moth_plant",
                    planty_plant_content.models.ChoiceArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("1", "Raupenfutterpflanze(Schmetterling)"),
                                ("2", "Raupenfutterpflanze (Nachtfalter)"),
                                ("3", "Nektarpflanze(Schmetterling)"),
                                ("4", "Nektarpflanze(Nachtfalter)"),
                                ("5", "Nutzung von Schmetterlingen"),
                                ("6", "Nutzung von Nachtfaltern"),
                            ],
                            max_length=2,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Falterpflanze",
                    ),
                ),
                (
                    "extra_moth",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Hinweise zur Falterpflanze",
                    ),
                ),
                (
                    "bird_plant",
                    planty_plant_content.models.ChoiceArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("1", "Futter"),
                                ("2", "Nistplatz"),
                                ("3", "Nistmaterial"),
                            ],
                            max_length=2,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Vogelnutzpflanze",
                    ),
                ),
                (
                    "extra_bird",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Hinweise zur Vogelnutzpflanze",
                    ),
                ),
                (
                    "extra_animal",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Weitere Nutzungen durch Tiere",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nutzbarkeit Fauna",
                "verbose_name_plural": "Nutzbarkeiten Fauna",
            },
        ),
        migrations.CreateModel(
            name="HumanUsability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medical_use",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Medizinischer Nutzen",
                    ),
                ),
                (
                    "edible",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Essbarkeit der Bestandteile",
                    ),
                ),
                (
                    "use_of_parts",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Nutzung und Verarbeitung der Bestandteile",
                    ),
                ),
                (
                    "wood_use",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Holznutzung",
                    ),
                ),
                (
                    "wood_properties",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Holzeigenschaften ",
                    ),
                ),
                (
                    "religious_meaning",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Kulturelle Bedeutung/ Volksglaube",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nutzbarkeit Mensch ",
                "verbose_name_plural": "Nutzbarkeiten Mensch ",
            },
        ),
        migrations.CreateModel(
            name="Toxicity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "toxicity",
                    planty_plant_content.models.ChoiceArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("1", "ungiftig"),
                                ("2", "Laub"),
                                ("3", "leicht giftig"),
                                ("4", "Blüte leicht giftig"),
                                ("5", "Frucht leicht giftig"),
                                ("6", "Wurzel leicht giftig"),
                                ("7", "Laub giftig"),
                                ("8", "Blüte giftig"),
                                ("9", "Frucht giftig"),
                                ("10", "Wurzel giftig"),
                                ("11", "Laub stark giftig"),
                                ("12", "Blüte stark giftig"),
                                ("13", "Frucht stark giftig"),
                                ("14", "Wurzel stark giftig"),
                                ("15", "gesamte  Pflanze leicht giftig"),
                                ("16", "gesamte Pflanze giftig"),
                                ("17", "gesamte pflanze stark giftig"),
                                ("18", "phototoxisch"),
                                ("19", "kontaktgiftig"),
                            ],
                            max_length=2,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Giftigkeit",
                    ),
                ),
                (
                    "extra_toxicity",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Hinweise zur Giftigkeit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giftigkeit",
                "verbose_name_plural": "Giftigkeiten",
            },
        ),
        migrations.CreateModel(
            name="Usability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fauna_usability",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usability",
                        to="planty_plant_content.FaunaUsability",
                        verbose_name="Nutzbarkeit Fauna",
                    ),
                ),
                (
                    "human_usability",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usability",
                        to="planty_plant_content.HumanUsability",
                        verbose_name="Nutzbarkeit Mensch ",
                    ),
                ),
                (
                    "plant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usability",
                        to="planty_plant_content.Plant",
                        verbose_name="Pflanze",
                    ),
                ),
                (
                    "toxicity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usability",
                        to="planty_plant_content.Toxicity",
                        verbose_name="Giftigkeit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nutzbarkeit",
                "verbose_name_plural": "Nutzbarkeiten",
            },
        ),
    ]
