# Generated by Django 3.0.11 on 2022-04-06 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planty_plant_content', '0008_diseases'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, max_length=500, null=True, verbose_name='Informatives')),
                ('literature', models.TextField(blank=True, max_length=500, null=True, verbose_name='Literatur')),
                ('geo_data', models.TextField(blank=True, max_length=500, null=True, verbose_name='Verortung am Hochschulstandort')),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_information', to='planty_plant_content.Plant', verbose_name='Pflanze')),
            ],
            options={
                'verbose_name': 'Informatives',
                'verbose_name_plural': 'Informatives',
            },
        ),
    ]
