# Generated by Django 3.0.11 on 2022-05-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planty_plant_content", "0009_generalinformation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ecologyandnatlocation",
            options={
                "verbose_name": "Ökologie und Naturstandort",
                "verbose_name_plural": "Ökologie und Naturstandort",
            },
        ),
        migrations.AlterField(
            model_name="root",
            name="spread",
            field=models.TextField(
                blank=True,
                help_text="Vegetative Ausbreitung und Speicherorgane",
                max_length=500,
                null=True,
                verbose_name="Vegetative Ausbreitung und Speicherorgane",
            ),
        ),
    ]
