# Generated by Django 3.0.11 on 2022-11-15 18:43

from django.db import migrations, models
import planty_plant_content.models


class Migration(migrations.Migration):

    dependencies = [
        ('planty_plant_content', '0010_auto_20220502_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bark',
            name='surface',
            field=models.TextField(blank=True, help_text='Jung- und Altzustand', max_length=500, null=True, verbose_name='Oberfläche/Struktur'),
        ),
        migrations.AlterField(
            model_name='faunausability',
            name='moth_plant',
            field=planty_plant_content.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('1', 'Raupenfutterpflanze (Schmetterling)'), ('2', 'Raupenfutterpflanze (Nachtfalter)'), ('3', 'Nektarpflanze (Schmetterling)'), ('4', 'Nektarpflanze (Nachtfalter)'), ('5', 'Nutzung von Schmetterlingen'), ('6', 'Nutzung von Nachtfaltern')], max_length=2), blank=True, null=True, size=None, verbose_name='Falterpflanze'),
        ),
        migrations.AlterField(
            model_name='humanusability',
            name='religious_meaning',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Etymologie und kulturelle Bedeutung'),
        ),
        migrations.AlterField(
            model_name='natoccurence',
            name='endangerment',
            field=models.CharField(blank=True, choices=[('1', '0: ausgestorben oder verschollen'), ('2', '1: vom Aussterben bedroht'), ('3', '2: stark gefährdet'), ('4', '3: gefährdet'), ('5', '4: potentiell gefährdet (nur bei Roten Listen der Länder; soll künftig durch R ersetzt werden)'), ('6', 'V: Vorwarnliste, Bestände zurückgehend'), ('7', 'R: extrem selten (entspricht 4 bei den Roten Listen der Länder; s.o.)'), ('8', 'G: Gefährdung anzunehmen'), ('9', 'D: Daten mangelhaft'), ('10', 'n: Neophyt'), ('11', '*: ungefährdet')], help_text='Gefährdung nach Rote Liste', max_length=2, null=True, verbose_name='Gefährdung '),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='family',
            field=models.CharField(choices=[('1', 'Anacardiaceae (Sumachgewächse)'), ('2', 'Amaryllidaceae (Narzissengewächse)'), ('3', 'Apiaceae (Doldenblütler)'), ('4', 'Aristolochiaceae (Osterluzeigewächse)'), ('5', 'Asteraceae (Korbblütler)'), ('6', 'Berberidaceae (Berberitzengewächse)'), ('7', 'Betulaceae (Birkengewächse)'), ('8', 'Bignoniaceae (Trompetenbaumgewächse)'), ('9', 'Boraginaceae (Raublattgewächse)'), ('10', 'Brassicaceae (Kreuzblütengewächse)'), ('11', 'Buddlejaceae (Schmetterlingsfliedergewächse)'), ('12', 'Buxaceae (Buchsbaumgewächse)'), ('13', 'Campanulaceae (Glockenblumengewächse)'), ('14', 'Caryophyllaceae (Nelkengewächse)'), ('15', 'Celastraceae (Spindelbaumgewächse)'), ('16', 'Cercidiphyllaceae (Kuchenbaumgewächse)'), ('17', 'Cornaceae (Hartriegelgewächse)'), ('18', 'Cupressaceae (Zypressengewächse)'), ('19', 'Ericaceae (Heidekrautgewächse)'), ('20', 'Euphorbiaceae (Wolfsmilchgewächse)'), ('21', 'Fabaceae (Hülsenfrüchtler)'), ('22', 'Fagaceae (Buchengewächse)'), ('23', 'Gentianaceae (Enziangewächse)'), ('24', 'Iridaceae (Schwertliliengewächse)'), ('25', 'Lamiaceae (Lippenblütler)'), ('26', 'Liliaceae (Liliengewächse)'), ('27', 'Magnoliaceae (Magnoliengewächse)'), ('28', 'Malvaceae (Malvengewächse)'), ('29', 'Nymphaeaceae (Seerosengewächse)'), ('30', 'Orchidaceae (Orchideengewächse)'), ('31', 'Papaveraceae (Mohngewächse)'), ('32', 'Pinaceae (Kieferngewächse)'), ('33', 'Poaceae (Süssgräser)'), ('34', 'Primulaceae (Primelgewächse)'), ('35', 'Ranunculaceae (Hahnenfussgewächse)'), ('36', 'Rosaceae (Rosengewächse)'), ('37', 'Sapindaceae (Seifenbaumgewächse)'), ('38', 'Scrophulariaceae (Rachenblütler)'), ('39', 'Simaroubaceae (Bittereschengewächse)'), ('40', 'Solanaceae (Nachtschattengewächse)')], max_length=36, verbose_name='Familie - botanischer Name (deutscher Name)'),
        ),
        migrations.AlterField(
            model_name='toxicity',
            name='toxicity',
            field=planty_plant_content.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('1', 'ungiftig'), ('2', 'Laub'), ('3', 'leicht giftig'), ('4', 'Blüte leicht giftig'), ('5', 'Frucht leicht giftig'), ('6', 'Wurzel leicht giftig'), ('7', 'Laub giftig'), ('8', 'Blüte giftig'), ('9', 'Frucht giftig'), ('10', 'Wurzel giftig'), ('11', 'Laub stark giftig'), ('12', 'Blüte stark giftig'), ('13', 'Frucht stark giftig'), ('14', 'Wurzel stark giftig'), ('15', 'gesamte  Pflanze leicht giftig'), ('16', 'gesamte Pflanze giftig'), ('17', 'gesamte pflanze stark giftig'), ('18', 'phototoxisch'), ('19', 'kontaktgiftig'), ('20', 'Rinde giftig'), ('21', 'Samen giftig'), ('22', 'Samen leicht giftig')], max_length=2), blank=True, null=True, size=None, verbose_name='Giftigkeit'),
        ),
    ]
