# Generated by Django 3.0.11 on 2022-11-22 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planty_plant_content', '0010_auto_20220502_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='habitat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='planty_plant_content.Habitat', verbose_name='Standort'),
        ),
    ]
