# Generated by Django 3.2.16 on 2023-01-20 15:14

from django.db import migrations, models
import django.db.models.deletion
import planty_plant_content.models


class Migration(migrations.Migration):

    dependencies = [
        ('planty_plant_content', '0012_function_climate_suitability'),
    ]

    operations = [
        migrations.AddField(
            model_name='blossom',
            name='housing',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Häusigkeit'),
        ),
        migrations.AddField(
            model_name='blossom',
            name='sexus',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Geschlechtlichkeit'),
        ),
        migrations.AlterField(
            model_name='humanusability',
            name='religious_meaning',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Etymologie und kulturelle Bedeutung'),
        ),
        migrations.AlterField(
            model_name='living',
            name='life_span',
            field=models.CharField(blank=True, choices=[('1', 'ausdauernd, sehr kurz überdauernd ( < 50 J)?'), ('2', 'ausdauernd, kurz überdauernd(50 - 100J)'), ('3', 'ausdauernd, mäßig dauerhaft(100 - 300J)'), ('4', 'ausdauernd, dauerhaft(300 - 500J)'), ('5', 'ausdauernd, sehr dauerhaft(ü 500J)')], max_length=44, null=True, verbose_name='Lebensdauer'),
        ),
        migrations.AlterField(
            model_name='natbehavior',
            name='zeiger_value',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nat_behavior', to='planty_plant_content.zeigervalues', verbose_name='Zeigerwerte nach Ellenberg'),
        ),
        migrations.AlterField(
            model_name='natoccurence',
            name='endangerment',
            field=models.CharField(blank=True, choices=[('1', '0: ausgestorben oder verschollen'), ('2', '1: vom Aussterben bedroht'), ('3', '2: stark gefährdet'), ('4', '3: gefährdet'), ('5', '4: potentiell gefährdet (nur bei Roten Listen der Länder; soll künftig durch R ersetzt werden)'), ('6', 'V: Vorwarnliste, Bestände zurückgehend'), ('7', 'R: extrem selten (entspricht 4 bei den Roten Listen der Länder; s.o.)'), ('8', 'G: Gefährdung anzunehmen'), ('9', 'D: Daten mangelhaft'), ('10', '*: ungefährdet')], help_text='Gefährdung nach Rote Liste', max_length=2, null=True, verbose_name='Gefährdung '),
        ),
        migrations.AlterField(
            model_name='reproductionandproduction',
            name='reproduction_type',
            field=planty_plant_content.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('1', 'Aussaat'), ('2', 'Stecklingsvermehrung'), ('3', 'Brutknöllchen'), ('4', 'Ableger'), ('5', 'Veredelung')], max_length=2), blank=True, null=True, size=None, verbose_name='Art der Vermehrung'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='family',
            field=models.CharField(choices=[('1', 'Amaryllidaceae (Narzissengewächse)'), ('2', 'Anacardiaceae (Sumachgewächse)'), ('3', 'Apiaceae (Doldenblütler)'), ('4', 'Aquifoliaceae (Stechpalmengewächse)'), ('5', 'Araliaceae (Efeugewächse)'), ('6', 'Aristolochiaceae (Osterluzeigewächse)'), ('7', 'Asteraceae (Korbblütler)'), ('8', 'Berberidaceae (Berberitzengewächse)'), ('9', 'Betulaceae (Birkengewächse)'), ('10', 'Bignoniaceae (Trompetenbaumgewächse)'), ('11', 'Boraginaceae (Raublattgewächse)'), ('12', 'Brassicaceae (Kreuzblütengewächse)'), ('13', 'Buddlejaceae (Schmetterlingsfliedergewächse)'), ('14', 'Buxaceae (Buchsbaumgewächse)'), ('15', 'Campanulaceae (Glockenblumengewächse)'), ('16', 'Caprifoliaceae (Geißblattgewächse)'), ('17', 'Caryophyllaceae (Nelkengewächse)'), ('18', 'Celastraceae (Spindelbaumgewächse)'), ('19', 'Cercidiphyllaceae (Kuchenbaumgewächse)'), ('20', 'Cornaceae (Hartriegelgewächse)'), ('21', 'Cupressaceae (Zypressengewächse)'), ('22', 'Elaeagnaceae (Ölweidengewächse)'), ('23', 'Ericaceae (Heidekrautgewächse)'), ('24', 'Euphorbiaceae (Wolfsmilchgewächse)'), ('25', 'Fabaceae (Hülsenfrüchtler)'), ('26', 'Fagaceae (Buchengewächse)'), ('27', 'Gentianaceae (Enziangewächse)'), ('28', 'Ginkgoaceae (Ginkgogewächse)'), ('29', 'Hamamelidaceae (Zaubernussgewächse)'), ('30', 'Hydrangeaceae, Hortensiengewächse'), ('31', 'Iridaceae (Schwertliliengewächse)'), ('32', 'Juglandaceae (Walnußgewächse)'), ('33', 'Lamiaceae (Lippenblütler)'), ('34', 'Liliaceae (Liliengewächse)'), ('35', 'Magnoliaceae (Magnoliengewächse)'), ('36', 'Malvaceae (Malvengewächse)'), ('37', 'Moraceae (Maulbeerbaumgewächse)'), ('38', 'Nymphaeaceae (Seerosengewächse)'), ('39', 'Oleaceae (Ölbaumgewächse)'), ('40', 'Orchidaceae (Orchideengewächse)'), ('41', 'Papaveraceae (Mohngewächse)'), ('42', 'Pinaceae (Kieferngewächse)'), ('43', 'Platanaceae (Platanengewächse)'), ('44', 'Poaceae (Süssgräser)'), ('45', 'Polygonaceae (Knöterichgewächse)'), ('46', 'Primulaceae (Primelgewächse)'), ('47', 'Ranunculaceae (Hahnenfussgewächse)'), ('48', 'Rosaceae (Rosengewächse)'), ('49', 'Salicaceae (Weidengewächse)'), ('50', 'Sapindaceae (Seifenbaumgewächse'), ('51', 'Scrophulariaceae (Braunwurzgewächse)'), ('52', 'Scrophulariaceae (Rachenblütler)'), ('53', 'Simaroubaceae (Bittereschengewächse)'), ('54', 'Solanaceae (Nachtschattengewächse)'), ('55', 'Taxaceae (Eibengewächse)'), ('56', 'Taxodiaceae (Sumpfzypressengewächse)'), ('57', 'Thymelaeaceae (Seidelbastgewächse )'), ('58', 'Ulmaceae (Ulmengewächse)'), ('59', 'Vitaceae (Rebengewächse)')], max_length=36, verbose_name='Familie - botanischer Name (deutscher Name)'),
        ),
        migrations.AlterField(
            model_name='toxicity',
            name='toxicity',
            field=planty_plant_content.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('1', 'Blüte giftig'), ('2', 'Blüte leicht giftig'), ('3', 'Blüte stark giftig'), ('4', 'Frucht giftig'), ('5', 'Frucht leicht giftig'), ('6', 'Frucht stark giftig'), ('7', 'gesamte Pflanze leicht giftig'), ('8', 'gesamte Pflanze giftig'), ('9', 'gesamte Pflanze stark giftig'), ('10', 'Laub giftig'), ('11', 'Laub leicht giftig'), ('12', 'Laub stark giftig'), ('13', 'Rinde giftig'), ('14', 'Samen giftig'), ('15', 'Samen leicht giftig'), ('16', 'Samen stark giftig'), ('17', 'Wurzel giftig'), ('18', 'Wurzel leicht giftig'), ('19', 'Wurzel stark giftig'), ('20', 'kontaktgiftig'), ('21', 'phototoxisch'), ('22', 'ungiftig')], max_length=2), blank=True, null=True, size=None, verbose_name='Giftigkeit'),
        ),
    ]
