# Generated by Django 3.0.11 on 2023-01-30 10:40

from django.db import migrations, models
import django.db.models.deletion
import planty_plant_content.models


class Migration(migrations.Migration):

    dependencies = [
        ('planty_plant_content', '0013_auto_20230120_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blossom',
            name='pollination',
            field=planty_plant_content.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('1', 'abiotische Bestäubung'), ('2', 'Fledermausbestäubung'), ('3', 'Geitonogamie'), ('4', 'Insektenbestäubung'), ('5', 'Kleistogamie'), ('6', 'Pseudokleistogamie'), ('7', 'Selbstbestäubung'), ('8', 'Schneckenbestäubung'), ('9', 'Vogelbestäubung'), ('10', 'Wasserbestäubung'), ('11', 'Windbestäubung'), ('12', 'Tierbestäubung')], max_length=2), blank=True, help_text='für generative Vermehrung', null=True, size=None, verbose_name='Bestäubungsfaktoren '),
        ),
        migrations.AlterField(
            model_name='natbehavior',
            name='zeiger_value',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nat_behavior', to='planty_plant_content.ZeigerValues', verbose_name='Zeigerwerte nach Ellenberg'),
        ),
        migrations.AlterField(
            model_name='reproductionandproduction',
            name='reproduction_type',
            field=planty_plant_content.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('1', 'Aussaat'), ('2', 'Stecklingsvermehrung'), ('3', 'Brutknöllchen'), ('4', 'Ableger'), ('5', 'Veredlung')], max_length=2), blank=True, null=True, size=None, verbose_name='Art der Vermehrung'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='family',
            field=models.CharField(choices=[('1', 'Amaryllidaceae (Narzissengewächse)'), ('2', 'Anacardiaceae (Sumachgewächse)'), ('3', 'Apiaceae (Doldenblütler)'), ('4', 'Aquifoliaceae (Stechpalmengewächse)'), ('5', 'Araliaceae (Efeugewächse)'), ('6', 'Aristolochiaceae (Osterluzeigewächse)'), ('7', 'Asteraceae (Korbblütler)'), ('8', 'Berberidaceae (Berberitzengewächse)'), ('9', 'Betulaceae (Birkengewächse)'), ('10', 'Bignoniaceae (Trompetenbaumgewächse)'), ('11', 'Boraginaceae (Raublattgewächse)'), ('12', 'Brassicaceae (Kreuzblütengewächse)'), ('13', 'Buddlejaceae (Schmetterlingsfliedergewächse)'), ('14', 'Buxaceae (Buchsbaumgewächse)'), ('15', 'Campanulaceae (Glockenblumengewächse)'), ('16', 'Caprifoliaceae (Geißblattgewächse)'), ('17', 'Caryophyllaceae (Nelkengewächse)'), ('18', 'Celastraceae (Spindelbaumgewächse)'), ('19', 'Cercidiphyllaceae (Kuchenbaumgewächse)'), ('20', 'Cornaceae (Hartriegelgewächse)'), ('21', 'Cupressaceae (Zypressengewächse)'), ('22', 'Elaeagnaceae (Ölweidengewächse)'), ('23', 'Ericaceae (Heidekrautgewächse)'), ('24', 'Euphorbiaceae (Wolfsmilchgewächse)'), ('25', 'Fabaceae (Hülsenfrüchtler)'), ('26', 'Fagaceae (Buchengewächse)'), ('27', 'Gentianaceae (Enziangewächse)'), ('28', 'Ginkgoaceae (Ginkgogewächse)'), ('29', 'Hamamelidaceae (Zaubernussgewächse)'), ('30', 'Hydrangeaceae, Hortensiengewächse'), ('31', 'Iridaceae (Schwertliliengewächse)'), ('32', 'Juglandaceae (Walnußgewächse)'), ('33', 'Lamiaceae (Lippenblütler)'), ('34', 'Liliaceae (Liliengewächse)'), ('35', 'Magnoliaceae (Magnoliengewächse)'), ('36', 'Malvaceae (Malvengewächse)'), ('37', 'Moraceae (Maulbeerbaumgewächse)'), ('38', 'Nymphaeaceae (Seerosengewächse)'), ('39', 'Oleaceae (Ölbaumgewächse)'), ('40', 'Orchidaceae (Orchideengewächse)'), ('41', 'Papaveraceae (Mohngewächse)'), ('42', 'Pinaceae (Kieferngewächse)'), ('43', 'Platanaceae (Platanengewächse)'), ('44', 'Poaceae (Süssgräser)'), ('45', 'Polygonaceae (Knöterichgewächse)'), ('46', 'Primulaceae (Primelgewächse)'), ('47', 'Ranunculaceae (Hahnenfussgewächse)'), ('48', 'Rosaceae (Rosengewächse)'), ('49', 'Salicaceae (Weidengewächse)'), ('50', 'Sapindaceae (Seifenbaumgewächse)'), ('51', 'Scrophulariaceae (Braunwurzgewächse)'), ('52', 'Scrophulariaceae (Rachenblütler)'), ('53', 'Simaroubaceae (Bittereschengewächse)'), ('54', 'Solanaceae (Nachtschattengewächse)'), ('55', 'Taxaceae (Eibengewächse)'), ('56', 'Taxodiaceae (Sumpfzypressengewächse)'), ('57', 'Thymelaeaceae (Seidelbastgewächse)'), ('58', 'Ulmaceae (Ulmengewächse)'), ('59', 'Vitaceae (Rebengewächse)')], max_length=36, verbose_name='Familie - botanischer Name (deutscher Name)'),
        ),
    ]
