# Generated by Django 3.2.16 on 2023-07-06 16:00

from django.db import migrations, models


def move_de_name_to_general_info_name(apps, schema_editor):
    """
    Create and populate a model instance of GeneralInforamtion and link it to the
    respective plant.
    """
    Plant = apps.get_model("planty_plant_content", "Plant")

    for obj in Plant.objects.all():
        general_info = obj.general_information
        general_info.name = obj.living.de_name
        general_info.save()


def move_name_to_taxonomy_de_name(apps, schema_editor):
    """
    Populate the fields of a Plant model instance form the linked GeneralInformation
    model instance.
    """
    Plant = apps.get_model("planty_plant_content", "Plant")

    for obj in Plant.objects.all():
        living = obj.living
        living.de_name = obj.general_information.name
        living.save()


class Migration(migrations.Migration):

    dependencies = [
        ('planty_plant_content', '0016_alter_ecologyandnatlocation_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='name',
            field=models.CharField(default='Test', max_length=100, verbose_name='Deutscher Name'),
            preserve_default=False,
        ),
        migrations.RunPython(
            move_de_name_to_general_info_name, move_name_to_taxonomy_de_name
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='de_name',
        )
    ]
