# Generated by Django 3.2.16 on 2023-07-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planty_plant_content', '0019_auto_20230713_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bark',
            name='structure',
        ),
    ]
