# Generated by Django 3.2.16 on 2023-07-13 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planty_plant_content', '0020_remove_bark_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usability',
            name='fauna_usability',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usability', to='planty_plant_content.faunausability', verbose_name='Nutzbarkeit Fauna'),
        ),
        migrations.AlterField(
            model_name='usability',
            name='human_usability',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usability', to='planty_plant_content.humanusability', verbose_name='Nutzbarkeit Mensch '),
        ),
        migrations.AlterField(
            model_name='usability',
            name='toxicity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usability', to='planty_plant_content.toxicity', verbose_name='Giftigkeit'),
        ),
    ]
