# Generated by Django 3.2.16 on 2023-07-13 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planty_plant_content', '0021_auto_20230713_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='living',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy', to='planty_plant_content.living', verbose_name='Lebensweise'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='plant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy', to='planty_plant_content.plant', verbose_name='Pflanze'),
        ),
    ]
