# Generated by Django 3.2.16 on 2023-07-13 14:08

from django.db import migrations, models


def move_name_to_sub_name(apps, schema_editor):
    GeneralInformation = apps.get_model("planty_plant_content", "GeneralInformation")
    for obj in GeneralInformation.objects.all():
        obj.sub_name = obj.name
        obj.save()


def move_sub_name_to_name(apps, schema_editor):
    GeneralInformation = apps.get_model("planty_plant_content", "GeneralInformation")
    for obj in GeneralInformation.objects.all():
        obj.name = obj.sub_name
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('planty_plant_content', '0023_alter_appearance_bark'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='sub_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Deutscher Name'),
        ),
        migrations.RunPython(move_name_to_sub_name, move_sub_name_to_name)
    ]
