# Generated by Django 3.2.16 on 2024-03-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planty_plant_content', '0026_auto_20240325_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='family',
            field=models.CharField(choices=[('60', 'Adoxaceae (Moschuskrautgewächse)'), ('1', 'Amaryllidaceae (Amaryllisgewächse)'), ('2', 'Anacardiaceae (Sumachgewächse)'), ('3', 'Apiaceae (Doldenblütler)'), ('4', 'Aquifoliaceae (Stechpalmengewächse)'), ('5', 'Araliaceae (Araliengewächse)'), ('6', 'Aristolochiaceae (Osterluzeigewächse)'), ('7', 'Asteraceae (Korbblütler)'), ('8', 'Berberidaceae (Berberitzengewächse)'), ('9', 'Betulaceae (Birkengewächse)'), ('10', 'Bignoniaceae (Trompetenbaumgewächse)'), ('11', 'Boraginaceae (Raublattgewächse)'), ('12', 'Brassicaceae (Kreuzblütengewächse)'), ('13', 'Buddlejaceae (Schmetterlingsfliedergewächse)'), ('14', 'Buxaceae (Buchsbaumgewächse)'), ('15', 'Campanulaceae (Glockenblumengewächse)'), ('16', 'Caprifoliaceae (Geißblattgewächse)'), ('17', 'Caryophyllaceae (Nelkengewächse)'), ('18', 'Celastraceae (Spindelbaumgewächse)'), ('19', 'Cercidiphyllaceae (Kuchenbaumgewächse)'), ('20', 'Cornaceae (Hartriegelgewächse)'), ('21', 'Cupressaceae (Zypressengewächse)'), ('61', 'Ebenaceae (Ebenholzgewächse)'), ('22', 'Elaeagnaceae (Ölweidengewächse)'), ('23', 'Ericaceae (Heidekrautgewächse)'), ('24', 'Euphorbiaceae (Wolfsmilchgewächse)'), ('25', 'Fabaceae (Hülsenfrüchtler)'), ('26', 'Fagaceae (Buchengewächse)'), ('27', 'Gentianaceae (Enziangewächse)'), ('28', 'Ginkgoaceae (Ginkgogewächse)'), ('29', 'Hamamelidaceae (Zaubernussgewächse)'), ('30', 'Hydrangeaceae (Hortensiengewächse)'), ('31', 'Iridaceae (Schwertliliengewächse)'), ('32', 'Juglandaceae (Walnussgewächse)'), ('33', 'Lamiaceae (Lippenblütler)'), ('34', 'Liliaceae (Liliengewächse)'), ('62', 'Lythraceae (Weiderichgewächse)'), ('35', 'Magnoliaceae (Magnoliengewächse)'), ('36', 'Malvaceae (Malvengewächse)'), ('37', 'Moraceae (Maulbeergewächse)'), ('38', 'Nymphaeaceae (Seerosengewächse)'), ('39', 'Oleaceae (Ölbaumgewächse)'), ('40', 'Orchidaceae (Orchideengewächse)'), ('41', 'Papaveraceae (Mohngewächse)'), ('42', 'Pinaceae (Kieferngewächse)'), ('43', 'Platanaceae (Platanengewächse)'), ('44', 'Poaceae (Süßgräser)'), ('45', 'Polygonaceae (Knöterichgewächse)'), ('46', 'Primulaceae (Primelgewächse)'), ('47', 'Ranunculaceae (Hahnenfußgewächse)'), ('48', 'Rosaceae (Rosengewächse)'), ('63', 'Rutaceae (Rautengewächse)'), ('49', 'Salicaceae (Weidengewächse)'), ('50', 'Sapindaceae (Seifenbaumgewächse)'), ('51', 'Scrophulariaceae (Braunwurzgewächse)'), ('52', 'Scrophulariaceae (Rachenblütler)'), ('53', 'Simaroubaceae (Bittereschengewächse)'), ('54', 'Solanaceae (Nachtschattengewächse)'), ('55', 'Taxaceae (Eibengewächse)'), ('56', 'Taxodiaceae (Sumpfzypressengewächse)'), ('57', 'Thymelaeaceae (Seidelbastgewächse)'), ('58', 'Ulmaceae (Ulmengewächse)'), ('59', 'Vitaceae (Rebengewächse)')], max_length=36, verbose_name='Familie - botanischer Name (deutscher Name)'),
        ),
    ]
