# Generated by Django 3.2.16 on 2025-07-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planty_plant_content', '0028_alter_taxonomy_family'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sprout',
            new_name='PlantSprout',
        ),
    ]
