# Generated by Django 3.2.16 on 2025-07-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planty_plant_content', '0029_rename_sprout_plantsprout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantationandcare',
            name='plantation_time',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Empfohlener Pflanzzeitpunkt '),
        ),
    ]