# Generated by Django 3.2.16 on 2025-07-21 20:23

from django.db import migrations, models
import planty_plant_content.models


class Migration(migrations.Migration):

    dependencies = [
        ('planty_plant_content', '0030_alter_plantationandcare_plantation_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ('general_information__name',), 'verbose_name': 'Pflanze', 'verbose_name_plural': 'Pflanzen'},
        ),
        migrations.AlterField(
            model_name='habitatfactors',
            name='micro_climate',
            field=planty_plant_content.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('1', 'anspruchslos'), ('2', 'bevorzugt Kühle'), ('3', 'hitzeempfindlich'), ('4', 'exponierte Lage'), ('5', 'geschützte Lage'), ('6', 'windgeschützte Lage'), ('7', 'windexponierte Lage'), ('8', 'Laubmull'), ('9', 'empfindlich auf Laubmull'), ('10', 'luftfeuchte Lage'), ('11', 'lufttrockene Lage'), ('12', 'wärmeliebend'), ('13', 'hitzeverträglich'), ('14', 'trockenwarm')], max_length=2), blank=True, help_text='Fähigkeiten, Ansprüche', null=True, size=None, verbose_name='Mikroklima'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='family',
            field=models.CharField(choices=[('1', 'Acanthaceae (Akanthusgewächse)'), ('2', 'Adoxaceae (Moschuskrautgewächse)'), ('3', 'Amaryllidaceae (Narzissengewächse)'), ('4', 'Anacardiaceae (Sumachgewächse)'), ('5', 'Anthericaceae (Grasliliengewächse)'), ('6', 'Apiaceae (Doldenblütler)'), ('7', 'Aquifoliaceae (Stechpalmengewächse)'), ('8', 'Araliaceae (Efeugewächse)'), ('9', 'Aristolochiaceae (Osterluzeigewächse)'), ('10', 'Asparagaceae (Spargelgewächse)'), ('11', 'Asphodelaceae (Affodillgewächse)'), ('12', 'Asteraceae (Korbblütler)'), ('13', 'Berberidaceae (Berberitzengewächse)'), ('14', 'Betulaceae (Birkengewächse)'), ('15', 'Bignoniaceae (Trompetenbaumgewächse)'), ('16', 'Boraginaceae (Raublattgewächse)'), ('17', 'Brassicaceae (Kreuzblütengewächse)'), ('18', 'Buddlejaceae (Schmetterlingsfliedergewächse)'), ('19', 'Buxaceae (Buchsbaumgewächse)'), ('20', 'Campanulaceae (Glockenblumengewächse)'), ('21', 'Caprifoliaceae (Geißblattgewächse)'), ('22', 'Caryophyllaceae (Nelkengewächse)'), ('23', 'Celastraceae (Spindelbaumgewächse)'), ('24', 'Cercidiphyllaceae (Kuchenbaumgewächse)'), ('25', 'Cistaceae (Zistrosengewächse)'), ('26', 'Clusiaceae (Johanniskrautgewächse)'), ('27', 'Cornaceae (Hartriegelgewächse)'), ('28', 'Crassulaceae (Dickblattgewächse)'), ('29', 'Cupressaceae (Zypressengewächse)'), ('30', 'Dipsacaceae (Kardengewächse)'), ('31', 'Ebenaceae (Ebenholzgewächse)'), ('32', 'Elaeagnaceae (Ölweidengewächse)'), ('33', 'Ericaceae (Heidekrautgewächse)'), ('34', 'Euphorbiaceae (Wolfsmilchgewächse)'), ('35', 'Fabaceae (Hülsenfrüchtler)'), ('36', 'Fagaceae (Buchengewächse)'), ('37', 'Gentianaceae (Enziangewächse)'), ('38', 'Geraniaceae (Storchschnabelgewächse)'), ('39', 'Ginkgoaceae (Ginkgogewächse)'), ('40', 'Hamamelidaceae (Zaubernussgewächse)'), ('41', 'Hemerocallidaceae (Tagliliengewächse)'), ('42', 'Hydrangeaceae (Hortensiengewächse)'), ('43', 'Iridaceae (Schwertliliengewächse)'), ('44', 'Juglandaceae (Walnussgewächse)'), ('45', 'Lamiaceae (Lippenblütler)'), ('46', 'Liliaceae (Liliengewächse)'), ('47', 'Lythraceae (Weiderichgewächse)'), ('48', 'Magnoliaceae (Magnoliengewächse)'), ('49', 'Malvaceae (Malvengewächse)'), ('50', 'Moraceae (Maulbeergewächse)'), ('51', 'Nymphaeaceae (Seerosengewächse)'), ('52', 'Nyssaceae (Tupelogewächse)'), ('53', 'Oleaceae (Ölbaumgewächse)'), ('54', 'Onagraceae (Nachtkerzengewächse)'), ('55', 'Orchidaceae (Orchideengewächse)'), ('56', 'Paeoniaceae (Pfingstrosengewächse)'), ('57', 'Papaveraceae (Mohngewächse)'), ('58', 'Pinaceae (Kieferngewächse)'), ('59', 'Plantaginaceae (Wegerichgewächse)'), ('60', 'Platanaceae (Platanengewächse)'), ('61', 'Poaceae (Süßgräser)'), ('62', 'Polemoniaceae (Himmelsleitergewächse)'), ('63', 'Polygonaceae (Knöterichgewächse)'), ('64', 'Primulaceae (Primelgewächse)'), ('65', 'Ranunculaceae (Hahnenfußgewächse)'), ('66', 'Rhamnaceae (Kreuzdorngewächse)'), ('67', 'Rosaceae (Rosengewächse)'), ('68', 'Rubiaceae (Krappgewächse)'), ('69', 'Rutaceae (Rautengewächse)'), ('70', 'Salicaceae (Weidengewächse)'), ('71', 'Sapindaceae (Seifenbaumgewächse)'), ('72', 'Sapotaceae (Sapotengewächse)'), ('73', 'Saxifragaceae (Steinbrechgewächse)'), ('74', 'Scrophulariaceae (Braunwurzgewächse)'), ('75', 'Simaroubaceae (Bittereschengewächse)'), ('76', 'Solanaceae (Nachtschattengewächse)'), ('77', 'Styracaceae (Storaxbaumgewächse)'), ('78', 'Taxaceae (Eibengewächse)'), ('79', 'Taxodiaceae (Sumpfzypressengewächse)'), ('80', 'Thymelaeaceae (Seidelbastgewächse)'), ('81', 'Ulmaceae (Ulmengewächse)'), ('82', 'Valerianaceae (Baldriangewächse)'), ('83', 'Verbenaceae (Eisenkrautgewächse)'), ('84', 'Violaceae (Veilchengewächse)'), ('85', 'Vitaceae (Rebengewächse)')], max_length=36, verbose_name='Familie - botanischer Name (deutscher Name)'),
        ),
    ]
