# Generated by Django 3.0.11 on 2021-01-24 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planty_content', '0001_create_wine_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_hairy', models.CharField(blank=True, choices=[('kahl', 'kahl'), ('schwachwollig', 'schwachwollig'), ('wollig', 'wollig'), ('starkwollig', 'starkwollig'), ('filzig', 'filzig')], max_length=13, null=True, verbose_name='Behaarung der Triebspitze')),
                ('tip_type', models.CharField(choices=[('offen', 'offen'), ('halb offen bis offen', 'halb offen bis offen'), ('halb offen', 'halb offen'), ('geschlossen', 'geschlossen')], max_length=20, verbose_name='Typ der Triebspitze')),
                ('tip_color', models.CharField(max_length=200, verbose_name='Farbe der Triebspitze')),
                ('hairy', models.CharField(choices=[('ja', 'ja'), ('nein', 'nein')], max_length=4, verbose_name='Beharrung des Triebs')),
                ('color', models.CharField(max_length=200, verbose_name='Farbe des Triebs')),
                ('notes', models.TextField(blank=True, max_length=400, null=True, verbose_name='Besonderheiten')),
                ('wine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sprout', to='planty_content.Wine', verbose_name='Rebe')),
            ],
            options={
                'verbose_name': 'Trieb',
                'verbose_name_plural': 'Triebe',
            },
        ),
    ]
