# Generated by Django 3.0.11 on 2021-01-24 13:16

import django.db.models.deletion
import solid_backend.content.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planty_content", "0002_create_sprout_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="YoungLeaf",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=200, verbose_name="Farbe")),
                (
                    "lappung",
                    solid_backend.content.fields.FromToConcatField(
                        blank=True,
                        default="",
                        from_choices=(
                            ("ganzrandig", "ganzrandig"),
                            ("3-", "3-"),
                            ("3-lappig", "3-lappig"),
                            ("5-", "5-"),
                            ("5-lappig", "5-lappig"),
                            ("7-lappig", "7-lappig"),
                        ),
                        max_length=100,
                        to_choices=(
                            ("ganzrandig", "ganzrandig"),
                            ("3-", "3-"),
                            ("3-lappig", "3-lappig"),
                            ("5-", "5-"),
                            ("5-lappig", "5-lappig"),
                            ("7-lappig", "7-lappig"),
                        ),
                        verbose_name="Lappung",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="Besonderheiten",
                    ),
                ),
                (
                    "wine",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="young_leaf",
                        to="planty_content.Wine",
                        verbose_name="Rebe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Junges Blatt",
                "verbose_name_plural": "Junge Blätter",
            },
        ),
    ]
