# Generated by Django 3.0.11 on 2021-01-24 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planty_content', '0005_create_grape_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('flach', 'flach'), ('etwas flach', 'etwas flach'), ('rundlich', 'rundlich'), ('kurzoval', 'kurzoval'), ('eierförmig', 'eierförmig'), ('eierförmig abgestumpft', 'eierförmig abgestumpft'), ('verkehrt eierförmig', 'verkehrt eierförmig'), ('länglich', 'länglich'), ('langoval', 'langoval'), ('gebogen', 'gebogen')], max_length=22, verbose_name='Form')),
                ('size', models.CharField(choices=[('sehr klein', 'sehr klein'), ('klein', 'klein'), ('mittel', 'mittel'), ('groß', 'groß'), ('sehr groß', 'sehr groß')], max_length=10, verbose_name='Größe')),
                ('surface', models.CharField(choices=[('bepunktet', 'bepunktet'), ('beduftet', 'beduftet')], max_length=9, verbose_name='Oberfläche')),
                ('color', models.CharField(choices=[('weiß', 'weiß'), ('rot', 'rot'), ('blau', 'blau'), ('grüngelb', 'grüngelb'), ('rosa', 'rosa'), ('rot', 'rot'), ('rot-grau', 'rot-grau'), ('blauschwarz', 'blauschwarz'), ('rotschwarz', 'rotschwarz')], max_length=11, verbose_name='Farbe')),
                ('flesh_color', models.CharField(choices=[('ungefärbt', 'ungefärbt'), ('gefärbt', 'gefärbt')], max_length=9, verbose_name='Farbe des Fruchtfleischs')),
                ('armoa', models.CharField(choices=[('Muskatgeschmack', 'Muskatgeschmack'), ('Foxgeschmack', 'Foxgeschmack'), ('Spezielgeschmack', 'Spezielgeschmack')], max_length=16, verbose_name='Armoa')),
                ('notes', models.TextField(blank=True, max_length=400, null=True, verbose_name='Besonderheiten')),
                ('wine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='berry', to='planty_content.Wine', verbose_name='Rebe')),
            ],
            options={
                'verbose_name': 'Beere',
                'verbose_name_plural': 'Beeren',
            },
        ),
    ]
