# Generated by Django 3.0.11 on 2021-01-24 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planty_content', '0006_create_berry_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fork', models.CharField(choices=[('überwiegend zweigabelig', 'überwiegend zweigabelig'), ('überwiegend dreigabelig', 'überwiegend dreigabelig')], max_length=23, verbose_name='Gabelung')),
                ('series', models.CharField(choices=[('kontinuierlich', 'kontinuierlich'), ('diskontinuierlich', 'diskontinuierlich')], max_length=17, verbose_name='Rankenfolge')),
                ('color', models.CharField(blank=True, max_length=200, null=True, verbose_name='Farbe')),
                ('hairy', models.CharField(blank=True, max_length=200, null=True, verbose_name='Behaarung')),
                ('notes', models.TextField(blank=True, max_length=400, null=True, verbose_name='Besonderheiten')),
                ('wine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twine', to='planty_content.Wine', verbose_name='Rebe')),
            ],
            options={
                'verbose_name': 'Ranke',
                'verbose_name_plural': 'Ranken',
            },
        ),
    ]
