# Generated by Django 3.0.11 on 2021-01-24 14:54

import django.db.models.deletion
import solid_backend.content.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planty_content", "0007_create_twine_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Properties",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "claims",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Lageansprüche",
                    ),
                ),
                (
                    "dry_tolerant",
                    solid_backend.content.fields.FromToConcatField(
                        blank=True,
                        default="",
                        from_choices=(
                            ("gering", "gering"),
                            ("mittel", "mittel"),
                            ("gut", "gut"),
                            ("sehr gut", "sehr gut"),
                        ),
                        max_length=100,
                        to_choices=(
                            ("gering", "gering"),
                            ("mittel", "mittel"),
                            ("gut", "gut"),
                            ("sehr gut", "sehr gut"),
                        ),
                        verbose_name="Trockentoleranz",
                    ),
                ),
                (
                    "chlorose",
                    solid_backend.content.fields.FromToConcatField(
                        blank=True,
                        default="",
                        from_choices=(
                            ("gering", "gering"),
                            ("mittel", "mittel"),
                            ("gut", "gut"),
                            ("sehr gut", "sehr gut"),
                        ),
                        max_length=100,
                        to_choices=(
                            ("gering", "gering"),
                            ("mittel", "mittel"),
                            ("gut", "gut"),
                            ("sehr gut", "sehr gut"),
                        ),
                        verbose_name="Chlorosegestigkeit",
                    ),
                ),
                (
                    "aktive_chalk",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Aktivkalktoleranz",
                    ),
                ),
                (
                    "grow_pwr",
                    solid_backend.content.fields.FromToConcatField(
                        blank=True,
                        default="",
                        from_choices=(
                            ("sehr schwach", "sehr schwach"),
                            ("schwach", "schwach"),
                            ("mittel", "mittel"),
                            ("stark", "stark"),
                            ("sehr stark", "sehr stark"),
                        ),
                        max_length=100,
                        to_choices=(
                            ("sehr schwach", "sehr schwach"),
                            ("schwach", "schwach"),
                            ("mittel", "mittel"),
                            ("stark", "stark"),
                            ("sehr stark", "sehr stark"),
                        ),
                        verbose_name="Wuchskraft",
                    ),
                ),
                (
                    "roots",
                    solid_backend.content.fields.FromToConcatField(
                        blank=True,
                        default="",
                        from_choices=(
                            ("gering", "gering"),
                            ("mittel", "mittel"),
                            ("gut", "gut"),
                            ("sehr gut", "sehr gut"),
                        ),
                        max_length=100,
                        to_choices=(
                            ("gering", "gering"),
                            ("mittel", "mittel"),
                            ("gut", "gut"),
                            ("sehr gut", "sehr gut"),
                        ),
                        verbose_name="Bewurzelung",
                    ),
                ),
                (
                    "vegetation",
                    solid_backend.content.fields.FromToConcatField(
                        blank=True,
                        default="",
                        from_choices=(
                            ("sehr früh", "sehr früh"),
                            ("früh", "früh"),
                            ("mittel", "mittel"),
                            ("spät", "spät"),
                            ("sehr spät", "sehr spät"),
                        ),
                        max_length=100,
                        to_choices=(
                            ("sehr früh", "sehr früh"),
                            ("früh", "früh"),
                            ("mittel", "mittel"),
                            ("spät", "spät"),
                            ("sehr spät", "sehr spät"),
                        ),
                        verbose_name="Vegetationsabschluss",
                    ),
                ),
                (
                    "pfropf",
                    solid_backend.content.fields.FromToConcatField(
                        blank=True,
                        default="",
                        from_choices=(
                            ("gering", "gering"),
                            ("mittel", "mittel"),
                            ("gut", "gut"),
                            ("sehr gut", "sehr gut"),
                        ),
                        max_length=100,
                        to_choices=(
                            ("gering", "gering"),
                            ("mittel", "mittel"),
                            ("gut", "gut"),
                            ("sehr gut", "sehr gut"),
                        ),
                        verbose_name="Pfropfaffinität",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="Besonderheiten",
                    ),
                ),
                (
                    "wine",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="planty_content.Wine",
                        verbose_name="Rebe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eigenschaften",
                "verbose_name_plural": "Eigenschaften",
            },
        ),
    ]
