# Generated by Django 3.0.11 on 2021-02-26 09:57

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_alter_treenode_name_attributes"),
        ("planty_content", "0010_create_disease_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="tree_node",
            field=mptt.fields.TreeForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="profiles",
                related_query_name="profile",
                to="content.TreeNode",
            ),
        ),
    ]
