# Generated by Django 3.0.11 on 2021-02-26 10:00

from django.db import migrations


def populate_tree_node_with_systematics(apps, schema_editor):
    """
    Populate tree_node fields with systematics values.
    """
    Wine = apps.get_model("planty_content", "Wine")

    for obj in Wine.objects.all():
        obj.tree_node = obj.systematics
        obj.save()


def populate_systematics_with_tree_node(apps, schema_editor):
    """
    Populate systematics fields with tree_node values.
    """
    Wine = apps.get_model("planty_content", "Wine")

    for obj in Wine.objects.all():
        obj.systematics = obj.tree_node
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("planty_content", "0011_add_find_tree_node"),
    ]

    operations = [
        migrations.RunPython(
            populate_tree_node_with_systematics, populate_systematics_with_tree_node
        ),
    ]
