# Generated by Django 3.0.11 on 2021-03-12 09:53

from django.db import migrations, models
import solid_backend.content.fields


class Migration(migrations.Migration):

    dependencies = [
        ("planty_content", "0013_remove_systematics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grownleaf",
            name="ant_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fehlend", "fehlend"),
                    ("gering", "gering"),
                    ("mittel", "mittel"),
                    ("stark", "stark"),
                ],
                max_length=7,
                null=True,
                verbose_name="Anthocyanfärbung",
            ),
        ),
        migrations.AlterField(
            model_name="grownleaf",
            name="color",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Farbe"
            ),
        ),
        migrations.AlterField(
            model_name="grownleaf",
            name="edge_form",
            field=models.CharField(
                blank=True,
                choices=[("gesägt", "gesägt"), ("gezähnt", "gezähnt")],
                max_length=7,
                null=True,
                verbose_name="Randform",
            ),
        ),
        migrations.AlterField(
            model_name="grownleaf",
            name="form_spreite",
            field=models.CharField(
                blank=True,
                choices=[
                    ("keilförmig", "keilförmig"),
                    ("herzförmig", "herzförmig"),
                    ("fünfeckig", "fünfeckig"),
                    ("kreisförmig", "kreisförmig"),
                    ("nierenförmig", "nierenförmig"),
                ],
                max_length=12,
                null=True,
                verbose_name="Form der Blattspreite",
            ),
        ),
        migrations.AlterField(
            model_name="grownleaf",
            name="lappung",
            field=solid_backend.content.fields.FromToConcatField(
                blank=True,
                default="",
                from_choices=(
                    (None, "---------"),
                    ("ganzrandig", "ganzrandig"),
                    ("3-", "3-"),
                    ("3-lappig", "3-lappig"),
                    ("5-", "5-"),
                    ("5-lappig", "5-lappig"),
                    ("7-lappig", "7-lappig"),
                ),
                max_length=100,
                to_choices=(
                    (None, "---------"),
                    ("ganzrandig", "ganzrandig"),
                    ("3-", "3-"),
                    ("3-lappig", "3-lappig"),
                    ("5-", "5-"),
                    ("5-lappig", "5-lappig"),
                    ("7-lappig", "7-lappig"),
                ),
                verbose_name="Lappung",
            ),
        ),
        migrations.AlterField(
            model_name="grownleaf",
            name="shaft_form",
            field=solid_backend.content.fields.FromToConcatField(
                blank=True,
                default="",
                from_choices=(
                    (None, "---------"),
                    ("U-", "U-"),
                    ("U-förmig", "U-förmig"),
                    ("V-", "V-"),
                    ("V-förmig", "V-förmig"),
                    ("lyraförmig", "lyraförmig"),
                ),
                max_length=100,
                to_choices=(
                    (None, "---------"),
                    ("U-", "U-"),
                    ("U-förmig", "U-förmig"),
                    ("V-", "V-"),
                    ("V-förmig", "V-förmig"),
                    ("lyraförmig", "lyraförmig"),
                ),
                verbose_name="Stielbuchtform",
            ),
        ),
        migrations.AlterField(
            model_name="grownleaf",
            name="shaft_open",
            field=models.CharField(
                blank=True,
                choices=[
                    ("offen", "offen"),
                    ("geschlossen", "geschlossen"),
                    ("überlappend", "überlappend"),
                    ("weit überlappend", "weit überlappend"),
                ],
                max_length=16,
                null=True,
                verbose_name="Stielbuchtöffnungen",
            ),
        ),
        migrations.AlterField(
            model_name="grownleaf",
            name="structure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("glatt", "glatt"),
                    ("blasig", "blasig"),
                    ("gewellt", "gewellt"),
                ],
                max_length=7,
                null=True,
                verbose_name="Struktur",
            ),
        ),
        migrations.AlterField(
            model_name="phenology",
            name="bloom",
            field=solid_backend.content.fields.FromToConcatField(
                blank=True,
                default="",
                from_choices=(
                    (None, "---------"),
                    ("sehr früh", "sehr früh"),
                    ("früh", "früh"),
                    ("mittel", "mittel"),
                    ("spät", "spät"),
                    ("sehr spät", "sehr spät"),
                ),
                max_length=100,
                to_choices=(
                    (None, "---------"),
                    ("sehr früh", "sehr früh"),
                    ("früh", "früh"),
                    ("mittel", "mittel"),
                    ("spät", "spät"),
                    ("sehr spät", "sehr spät"),
                ),
                verbose_name="Blütezeitpunkt",
            ),
        ),
        migrations.AlterField(
            model_name="phenology",
            name="budding",
            field=solid_backend.content.fields.FromToConcatField(
                blank=True,
                default="",
                from_choices=(
                    (None, "---------"),
                    ("sehr früh", "sehr früh"),
                    ("früh", "früh"),
                    ("mittel", "mittel"),
                    ("spät", "spät"),
                    ("sehr spät", "sehr spät"),
                ),
                max_length=100,
                to_choices=(
                    (None, "---------"),
                    ("sehr früh", "sehr früh"),
                    ("früh", "früh"),
                    ("mittel", "mittel"),
                    ("spät", "spät"),
                    ("sehr spät", "sehr spät"),
                ),
                verbose_name="Austrieb",
            ),
        ),
        migrations.AlterField(
            model_name="phenology",
            name="ripening",
            field=solid_backend.content.fields.FromToConcatField(
                blank=True,
                default="",
                from_choices=(
                    (None, "---------"),
                    ("sehr früh", "sehr früh"),
                    ("früh", "früh"),
                    ("mittel", "mittel"),
                    ("spät", "spät"),
                    ("sehr spät", "sehr spät"),
                ),
                max_length=100,
                to_choices=(
                    (None, "---------"),
                    ("sehr früh", "sehr früh"),
                    ("früh", "früh"),
                    ("mittel", "mittel"),
                    ("spät", "spät"),
                    ("sehr spät", "sehr spät"),
                ),
                verbose_name="Reifezeit",
            ),
        ),
        migrations.AlterField(
            model_name="properties",
            name="chlorose",
            field=solid_backend.content.fields.FromToConcatField(
                blank=True,
                default="",
                from_choices=(
                    (None, "---------"),
                    ("gering", "gering"),
                    ("mittel", "mittel"),
                    ("gut", "gut"),
                    ("sehr gut", "sehr gut"),
                ),
                max_length=100,
                to_choices=(
                    (None, "---------"),
                    ("gering", "gering"),
                    ("mittel", "mittel"),
                    ("gut", "gut"),
                    ("sehr gut", "sehr gut"),
                ),
                verbose_name="Chlorosegestigkeit",
            ),
        ),
        migrations.AlterField(
            model_name="properties",
            name="dry_tolerant",
            field=solid_backend.content.fields.FromToConcatField(
                blank=True,
                default="",
                from_choices=(
                    (None, "---------"),
                    ("gering", "gering"),
                    ("mittel", "mittel"),
                    ("gut", "gut"),
                    ("sehr gut", "sehr gut"),
                ),
                max_length=100,
                to_choices=(
                    (None, "---------"),
                    ("gering", "gering"),
                    ("mittel", "mittel"),
                    ("gut", "gut"),
                    ("sehr gut", "sehr gut"),
                ),
                verbose_name="Trockentoleranz",
            ),
        ),
        migrations.AlterField(
            model_name="properties",
            name="pfropf",
            field=solid_backend.content.fields.FromToConcatField(
                blank=True,
                default="",
                from_choices=(
                    (None, "---------"),
                    ("gering", "gering"),
                    ("mittel", "mittel"),
                    ("gut", "gut"),
                    ("sehr gut", "sehr gut"),
                ),
                max_length=100,
                to_choices=(
                    (None, "---------"),
                    ("gering", "gering"),
                    ("mittel", "mittel"),
                    ("gut", "gut"),
                    ("sehr gut", "sehr gut"),
                ),
                verbose_name="Pfropfaffinität",
            ),
        ),
        migrations.AlterField(
            model_name="properties",
            name="roots",
            field=solid_backend.content.fields.FromToConcatField(
                blank=True,
                default="",
                from_choices=(
                    (None, "---------"),
                    ("gering", "gering"),
                    ("mittel", "mittel"),
                    ("gut", "gut"),
                    ("sehr gut", "sehr gut"),
                ),
                max_length=100,
                to_choices=(
                    (None, "---------"),
                    ("gering", "gering"),
                    ("mittel", "mittel"),
                    ("gut", "gut"),
                    ("sehr gut", "sehr gut"),
                ),
                verbose_name="Bewurzelung",
            ),
        ),
        migrations.AlterField(
            model_name="properties",
            name="vegetation",
            field=solid_backend.content.fields.FromToConcatField(
                blank=True,
                default="",
                from_choices=(
                    (None, "---------"),
                    ("sehr früh", "sehr früh"),
                    ("früh", "früh"),
                    ("mittel", "mittel"),
                    ("spät", "spät"),
                    ("sehr spät", "sehr spät"),
                ),
                max_length=100,
                to_choices=(
                    (None, "---------"),
                    ("sehr früh", "sehr früh"),
                    ("früh", "früh"),
                    ("mittel", "mittel"),
                    ("spät", "spät"),
                    ("sehr spät", "sehr spät"),
                ),
                verbose_name="Vegetationsabschluss",
            ),
        ),
        migrations.AlterField(
            model_name="wine",
            name="blossom",
            field=models.CharField(
                blank=True,
                choices=[
                    ("männlich", "männlich"),
                    ("weiblich", "weiblich"),
                    ("zwittrig", "zwittrig"),
                ],
                max_length=8,
                null=True,
                verbose_name="Blüte",
            ),
        ),
        migrations.AlterField(
            model_name="wine",
            name="cross_parents",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Kreuzungseltern"
            ),
        ),
        migrations.AlterField(
            model_name="wine",
            name="ger_name",
            field=models.CharField(max_length=200, verbose_name="Deutscher Name"),
        ),
        migrations.AlterField(
            model_name="youngleaf",
            name="color",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Farbe"
            ),
        ),
        migrations.AlterField(
            model_name="youngleaf",
            name="lappung",
            field=solid_backend.content.fields.FromToConcatField(
                blank=True,
                default="",
                from_choices=(
                    (None, "---------"),
                    ("ganzrandig", "ganzrandig"),
                    ("3-", "3-"),
                    ("3-lappig", "3-lappig"),
                    ("5-", "5-"),
                    ("5-lappig", "5-lappig"),
                    ("7-lappig", "7-lappig"),
                ),
                max_length=100,
                to_choices=(
                    (None, "---------"),
                    ("ganzrandig", "ganzrandig"),
                    ("3-", "3-"),
                    ("3-lappig", "3-lappig"),
                    ("5-", "5-"),
                    ("5-lappig", "5-lappig"),
                    ("7-lappig", "7-lappig"),
                ),
                verbose_name="Lappung",
            ),
        ),
    ]
