# Generated by Django 3.0.11 on 2021-03-12 10:02

from django.db import migrations
import solid_backend.content.fields


class Migration(migrations.Migration):

    dependencies = [
        ("planty_content", "0014_auto_20210312_1053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="properties",
            name="grow_pwr",
            field=solid_backend.content.fields.FromToConcatField(
                blank=True,
                default="",
                from_choices=(
                    (None, "---------"),
                    ("sehr schwach", "sehr schwach"),
                    ("schwach", "schwach"),
                    ("mittel", "mittel"),
                    ("stark", "stark"),
                    ("sehr stark", "sehr stark"),
                ),
                max_length=100,
                to_choices=(
                    (None, "---------"),
                    ("sehr schwach", "sehr schwach"),
                    ("schwach", "schwach"),
                    ("mittel", "mittel"),
                    ("stark", "stark"),
                    ("sehr stark", "sehr stark"),
                ),
                verbose_name="Wuchskraft",
            ),
        ),
    ]
