# Generated by Django 3.0.11 on 2021-03-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planty_content", "0015_auto_20210312_1102"),
    ]

    operations = [
        migrations.RemoveField(model_name="wine", name="ger_name",),
    ]
