# Generated by Django 3.0.11 on 2021-03-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planty_content", "0016_remove_ger_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprout",
            name="color",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Farbe des Triebs"
            ),
        ),
        migrations.AlterField(
            model_name="sprout",
            name="hairy",
            field=models.CharField(
                choices=[("ja", "ja"), ("nein", "nein")],
                max_length=4,
                null=True,
                verbose_name="Beharrung des Triebs",
            ),
        ),
        migrations.AlterField(
            model_name="sprout",
            name="tip_hairy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kahl", "kahl"),
                    ("schwachwollig", "schwachwollig"),
                    ("wollig", "wollig"),
                    ("starkwollig", "starkwollig"),
                    ("filzig", "filzig"),
                ],
                max_length=13,
                null=True,
                verbose_name="Beharrung der Triebspitze",
            ),
        ),
        migrations.AlterField(
            model_name="sprout",
            name="tip_type",
            field=models.CharField(
                choices=[
                    ("offen", "offen"),
                    ("halb offen bis offen", "halb offen bis offen"),
                    ("halb offen", "halb offen"),
                    ("geschlossen bis halboffen", "geschlossen bis halboffen"),
                    ("geschlossen", "geschlossen"),
                ],
                max_length=25,
                null=True,
                verbose_name="Typ der Triebspitze",
            ),
        ),
    ]
