# Generated by Django 3.0.11 on 2021-03-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planty_content", "0018_add_shouldered_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twine",
            name="fork",
            field=models.CharField(
                choices=[
                    ("überwiegend zweigabelig", "überwiegend zweigabelig"),
                    ("überwiegend dreigabelig", "überwiegend dreigabelig"),
                ],
                max_length=23,
                null=True,
                verbose_name="Gabelung",
            ),
        ),
        migrations.AlterField(
            model_name="twine",
            name="series",
            field=models.CharField(
                choices=[
                    ("kontinuierlich", "kontinuierlich"),
                    ("diskontinuierlich", "diskontinuierlich"),
                ],
                max_length=17,
                null=True,
                verbose_name="Rankenfolge",
            ),
        ),
    ]
