# Generated by Django 3.0.11 on 2021-03-29 12:38

import solid_backend.content.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planty_content", "0019_auto_20210329_1435"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disease",
            name="botrytis",
            field=models.CharField(
                choices=[("ja", "ja"), ("nein", "nein")],
                max_length=4,
                null=True,
                verbose_name="Anfälligkeit für Botrytis",
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="oidium",
            field=models.CharField(
                choices=[("ja", "ja"), ("nein", "nein")],
                max_length=4,
                null=True,
                verbose_name="Anfälligkeite für Oidium",
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="peronospora",
            field=models.CharField(
                choices=[("ja", "ja"), ("nein", "nein")],
                max_length=4,
                null=True,
                verbose_name="Anfälligkeit for Peronospora",
            ),
        ),
        migrations.AlterField(
            model_name="properties",
            name="chlorose",
            field=solid_backend.content.fields.FromToConcatField(
                blank=True,
                default="",
                from_choices=(
                    (None, "---------"),
                    ("gering", "gering"),
                    ("mittel", "mittel"),
                    ("gut", "gut"),
                    ("sehr gut", "sehr gut"),
                ),
                max_length=100,
                to_choices=(
                    (None, "---------"),
                    ("gering", "gering"),
                    ("mittel", "mittel"),
                    ("gut", "gut"),
                    ("sehr gut", "sehr gut"),
                ),
                verbose_name="Chlorosefestigkeit",
            ),
        ),
    ]
