# Generated by Django 3.0.11 on 2021-03-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planty_content", "0020_auto_20210329_1438"),
    ]

    operations = [
        migrations.RenameField(model_name="berry", old_name="armoa", new_name="aroma"),
        migrations.AlterField(
            model_name="berry",
            name="aroma",
            field=models.CharField(
                choices=[
                    ("Muskatgeschmack", "Muskatgeschmack"),
                    ("Foxgeschmack", "Foxgeschmack"),
                    ("Spezielgeschmack", "Spezielgeschmack"),
                ],
                max_length=16,
                verbose_name="Aroma",
            ),
        ),
        migrations.AlterField(
            model_name="berry",
            name="color",
            field=models.CharField(
                choices=[
                    ("weiß", "weiß"),
                    ("rot", "rot"),
                    ("gelb", "gelb"),
                    ("blau", "blau"),
                    ("grüngelb", "grüngelb"),
                    ("rosa", "rosa"),
                    ("rot", "rot"),
                    ("rot-grau", "rot-grau"),
                    ("blauschwarz", "blauschwarz"),
                    ("rotschwarz", "rotschwarz"),
                    ("bernsteinfarben", "bernsteinfarben"),
                ],
                max_length=15,
                verbose_name="Farbe",
            ),
        ),
    ]
