# Generated by Django 3.0.11 on 2021-03-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planty_content', '0022_auto_20210330_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprout',
            name='hairy',
            field=models.CharField(choices=[('ja', 'ja'), ('nein', 'nein')], max_length=4, null=True, verbose_name='Behaarung des Triebs'),
        ),
        migrations.AlterField(
            model_name='sprout',
            name='tip_hairy',
            field=models.CharField(blank=True, choices=[('kahl', 'kahl'), ('schwachwollig', 'schwachwollig'), ('wollig', 'wollig'), ('starkwollig', 'starkwollig'), ('filzig', 'filzig')], max_length=13, null=True, verbose_name='Behaarung der Triebspitze'),
        ),
    ]
