# Generated by Django 3.0.11 on 2021-03-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planty_content", "0023_auto_20210330_1451"),
    ]

    operations = [
        migrations.AlterField(
            model_name="berry",
            name="aroma",
            field=models.CharField(
                choices=[
                    ("Muskatgeschmack", "Muskatgeschmack"),
                    ("Foxgeschmack", "Foxgeschmack"),
                    ("Spezielgeschmack", "Spezielgeschmack"),
                ],
                max_length=16,
                null=True,
                blank=True,
                verbose_name="Aroma",
            ),
        ),
        migrations.AlterField(
            model_name="berry",
            name="surface",
            field=models.CharField(
                choices=[("bepunktet", "bepunktet"), ("beduftet", "beduftet")],
                max_length=9,
                null=True,
                blank=True,
                verbose_name="Oberfläche",
            ),
        ),
    ]
