# Generated by Django 3.0.11 on 2021-05-16 14:00

from django.db import migrations, models
import solid_backend.content.fields


class Migration(migrations.Migration):

    dependencies = [
        ('planty_content', '0029_auto_20210516_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berry',
            name='color',
            field=models.CharField(blank=True, choices=[('weiß', 'weiß'), ('rot', 'rot'), ('gelb', 'gelb'), ('blau', 'blau'), ('grüngelb', 'grüngelb'), ('rosa', 'rosa'), ('rot', 'rot'), ('rot-grau', 'rot-grau'), ('blauschwarz', 'blauschwarz'), ('rotschwarz', 'rotschwarz'), ('bernsteinfarben', 'bernsteinfarben')], max_length=15, null=True, verbose_name='Farbe'),
        ),
        migrations.AlterField(
            model_name='berry',
            name='flesh_color',
            field=models.CharField(blank=True, choices=[('ungefärbt', 'ungefärbt'), ('gefärbt', 'gefärbt')], max_length=9, null=True, verbose_name='Farbe des Fruchtfleischs'),
        ),
        migrations.AlterField(
            model_name='berry',
            name='form',
            field=models.CharField(blank=True, choices=[('flach', 'flach'), ('etwas flach', 'etwas flach'), ('rundlich', 'rundlich'), ('kurzoval', 'kurzoval'), ('eierförmig', 'eierförmig'), ('eierförmig abgestumpft', 'eierförmig abgestumpft'), ('verkehrt eierförmig', 'verkehrt eierförmig'), ('länglich', 'länglich'), ('langoval', 'langoval'), ('gebogen', 'gebogen')], max_length=22, null=True, verbose_name='Form'),
        ),
        migrations.AlterField(
            model_name='berry',
            name='size',
            field=solid_backend.content.fields.FromToConcatField(blank=True, default='', from_choices=((None, '---------'), ('sehr klein', 'sehr klein'), ('klein', 'klein'), ('mittel', 'mittel'), ('groß', 'groß'), ('sehr groß', 'sehr groß')), max_length=25, to_choices=((None, '---------'), ('sehr klein', 'sehr klein'), ('klein', 'klein'), ('mittel', 'mittel'), ('groß', 'groß'), ('sehr groß', 'sehr groß')), verbose_name='Größe'),
        ),
    ]
