# Generated by Django 3.0.11 on 2021-06-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planty_content', '0032_auto_20210608_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='blossom',
            field=models.CharField(blank=True, choices=[('männlich', 'männlich'), ('weiblich', 'weiblich'), ('zwittrig', 'zwittrig'), ('einhäusig', 'einhäusig'), ('zweihäusig', 'zweihäusig')], max_length=10, null=True, verbose_name='Blüte'),
        ),
    ]
