# Generated by Django 3.0.11 on 2022-12-09 11:05

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_treenode_name_attributes'),
        ('planty_content', '0033_auto_20210609_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='tree_node',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wine_related', related_query_name='wines', to='content.TreeNode'),
        ),
    ]
