# Generated by Django 3.2.16 on 2023-06-30 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planty_content', '0034_auto_20221209_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sorte')),
                ('synonyms', models.CharField(blank=True, max_length=200, null=True, verbose_name='Synonyme')),
                ('blossom', models.CharField(blank=True, choices=[('männlich', 'männlich'), ('weiblich', 'weiblich'), ('zwittrig', 'zwittrig'), ('einhäusig', 'einhäusig'), ('zweihäusig', 'zweihäusig')], max_length=10, null=True, verbose_name='Blüte')),
                ('cross_parents', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kreuzungseltern')),
                ('origin', models.CharField(help_text='Falls nicht bekannt "unbekannt" als Eingabe', max_length=200, verbose_name='Herkunft')),
                ('notes', models.TextField(blank=True, max_length=400, null=True, verbose_name='Anmerkungen')),
                ('wine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_information', to='planty_content.wine', verbose_name='Rebe')),
            ],
            options={
                'verbose_name': 'Allgemein',
                'verbose_name_plural': 'Allgemein',
            },
        ),
    ]
