# Generated by Django 3.2.16 on 2023-06-30 13:47

from django.db import migrations

def populate_general_information(apps, schema_editor):
    """
    Create and populate a model instance of GeneralInforamtion and link it to the
    respective plant.
    """
    Wine = apps.get_model("planty_content", "Wine")
    GeneralInformation = apps.get_model("planty_content", "GeneralInformation")

    for obj in Wine.objects.all():
        GeneralInformation.objects.create(
            name=obj.name,
            synonyms=obj.synonyms,
            blossom=obj.blossom,
            cross_parents=obj.cross_parents,
            origin=obj.origin,
            notes=obj.notes,
            wine=obj
        )

def populate_plant_fields(apps, schema_editor):
    """
    Populate the fields of a Plant model instance form the linked GeneralInformation
    model instance.
    """
    Wine = apps.get_model("planty_content", "Wine")

    for obj in Wine.objects.all():
        general_info = obj.general_information
        obj.name = general_info.name
        obj.synonyms = general_info.synonyms
        obj.blossom = general_info.blossom
        obj.cross_parents = general_info.cross_parents
        obj.origin = general_info.origin
        obj.notes = general_info.notes
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('planty_content', '0035_generalinformation'),
    ]

    operations = [
        migrations.RunPython(
            populate_general_information, populate_plant_fields
        )
    ]
