# Generated by Django 3.2.16 on 2023-06-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planty_content', '0036_migrate_plant_fields_to_general_information'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wine',
            options={'ordering': ('general_information__name',), 'verbose_name': 'Rebe', 'verbose_name_plural': 'Reben'},
        ),
        migrations.RemoveField(
            model_name='wine',
            name='blossom',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='cross_parents',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='name',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='synonyms',
        ),
    ]
