name: build-pr

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TRAVIS_CI: True
      PATH: ${{ github.workspace }}/.poetry/bin:${{ github.env.PATH }}
      POETRY_VERSION: 1.2.0
      POETRY_VIRTUALENVS_CREATE: false
      PROFILES_SERIALIZER: "planty_content.serializers.WineSerializer"

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Start PostgreSQL
      run: |
        sudo systemctl start postgresql.service
        sudo systemctl status postgresql.service

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        $HOME/.poetry/bin/poetry --version

    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.cache/pypoetry
        key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        $HOME/.poetry/bin/poetry install

    - name: Create database and user
      run: |
        sudo -u postgres psql -c "CREATE DATABASE test_db_app;" 
        sudo -u postgres psql -c "CREATE USER db_user WITH PASSWORD 'db_pass';" 
        sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE test_db_app TO db_user;"

    - name: Run tests
      run: |
        black . --check
        $HOME/.poetry/bin/poetry run pytest --cov=./

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true